name: Docker Image CI

on:
    workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rest-easy:0.0.1
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/rest-easy:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/rest-easy:cache,mode=max
        
      #- name: Build the Docker image
      #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
